global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tensorflow_serving'
    metrics_path: '/monitoring/prometheus/metrics'
    scheme: https
    static_configs:
      - targets: ['mualim-fth-pipeline-production.up.railway.app']